/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ComparatorRouteImport } from './routes/comparator'
import { Route as FixturesRouteImport } from './routes/fixtures'
import { Route as HeatmapRouteImport } from './routes/heatmap'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as ApiPublicEspnSyncRouteImport } from './routes/api/public/espn-sync'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ComparatorRoute = ComparatorRouteImport.update({
  id: '/comparator',
  path: '/comparator',
  getParentRoute: () => rootRouteImport,
} as any)
const FixturesRoute = FixturesRouteImport.update({
  id: '/fixtures',
  path: '/fixtures',
  getParentRoute: () => rootRouteImport,
} as any)
const HeatmapRoute = HeatmapRouteImport.update({
  id: '/heatmap',
  path: '/heatmap',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEspnSyncRoute = ApiPublicEspnSyncRouteImport.update({
  id: '/api/public/espn-sync',
  path: '/api/public/espn-sync',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/comparator': typeof ComparatorRoute
  '/fixtures': typeof FixturesRoute
  '/heatmap': typeof HeatmapRoute
  '/inventory': typeof InventoryRoute
  '/api/public/espn-sync': typeof ApiPublicEspnSyncRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/comparator': typeof ComparatorRoute
  '/fixtures': typeof FixturesRoute
  '/heatmap': typeof HeatmapRoute
  '/inventory': typeof InventoryRoute
  '/api/public/espn-sync': typeof ApiPublicEspnSyncRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/comparator': typeof ComparatorRoute
  '/fixtures': typeof FixturesRoute
  '/heatmap': typeof HeatmapRoute
  '/inventory': typeof InventoryRoute
  '/api/public/espn-sync': typeof ApiPublicEspnSyncRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/comparator'
    | '/fixtures'
    | '/heatmap'
    | '/inventory'
    | '/api/public/espn-sync'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/comparator'
    | '/fixtures'
    | '/heatmap'
    | '/inventory'
    | '/api/public/espn-sync'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/comparator'
    | '/fixtures'
    | '/heatmap'
    | '/inventory'
    | '/api/public/espn-sync'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ComparatorRoute: typeof ComparatorRoute
  FixturesRoute: typeof FixturesRoute
  HeatmapRoute: typeof HeatmapRoute
  InventoryRoute: typeof InventoryRoute
  ApiPublicEspnSyncRoute: typeof ApiPublicEspnSyncRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparator': {
      id: '/comparator'
      path: '/comparator'
      fullPath: '/comparator'
      preLoaderRoute: typeof ComparatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fixtures': {
      id: '/fixtures'
      path: '/fixtures'
      fullPath: '/fixtures'
      preLoaderRoute: typeof FixturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heatmap': {
      id: '/heatmap'
      path: '/heatmap'
      fullPath: '/heatmap'
      preLoaderRoute: typeof HeatmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/espn-sync': {
      id: '/api/public/espn-sync'
      path: '/api/public/espn-sync'
      fullPath: '/api/public/espn-sync'
      preLoaderRoute: typeof ApiPublicEspnSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ComparatorRoute: ComparatorRoute,
  FixturesRoute: FixturesRoute,
  HeatmapRoute: HeatmapRoute,
  InventoryRoute: InventoryRoute,
  ApiPublicEspnSyncRoute: ApiPublicEspnSyncRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
